server:
  port: 8080

spring:
  profiles:
    active: "dev"
  batch:
    jdbc:
      initialize-schema: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: non_null
---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: changemeinprod!
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 10
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_URL:localhost:5432}/postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 10